### ISSUE TITLE
tcdump: unknown file format

### ISSUE THREAD

**Issue by ghost** [jduncanator/iSniff#2]
When I pipe it into `tcdump`, I had to add this
```sh
❯ ./isniff | tcpdump -r-
Connected to ...<device uuid>...
tcpdump: unknown file format
```

```sh
❯ ./isniff | cat <(printf "\0\0\0\0") - | tcpdump -r -
Connected to ...<device uuid>...
reading from file -, link-type EN10MB (Ethernet)
...
...
```

**Comment by jduncanator** [comment]
Seems like this is an [issue specific to Apple's macOS port of libpcap and tcpdump](https://apple.stackexchange.com/questions/152682/why-does-tcpdump-not-recognise-piped-input). The problem here is that the Homebrew ports of those libraries don't have the same issue, so I can't do any sort of vendor detection for macOS without then breaking the Homebrew versions.

I'm happy to entertain some ideas for this one, but for the time being I'm going to mark this as closed as it's a bug with tcpdump, and out of my hands to resolve.
